#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Ensure running grub2-mkconfig results in BLS entries being updated
# See https://pkgs.devel.redhat.com/cgit/rpms/grub2/tree/0328-grub2-mkconfig-Pass-all-boot-params-when-used-by-ana.patch?h=rhel-9.3.0
mkdir /run/install
