export DIB_REPO_SETUP=${DIB_REPO_SETUP:-current-podified}
export DIB_REPO_SETUP_BRANCH=${DIB_REPO_SETUP_BRANCH:-master}
export DIB_REPO_SETUP_DISTRO_MIRROR=${DIB_REPO_SETUP_DISTRO_MIRROR:-''}
export DIB_REPO_SETUP_MIRROR=${DIB_REPO_SETUP_MIRROR:-https://trunk.rdoproject.org}